# Generated by Django 5.2.6 on 2025-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.CharField(default='Your University', max_length=200),
            preserve_default=False,
        ),
    ]
