# Generated by Django 5.2.6 on 2025-09-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_profile_uni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='chinese_title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='chinese_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='chinese_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='chinese_role',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uni',
            new_name='chinese_university',
        ),
        migrations.AddField(
            model_name='gallery',
            name='english_title',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='english_description',
            field=models.TextField(default='NAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='english_name',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='english_role',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='english_university',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
    ]
