# Generated by Django 5.2.6 on 2025-09-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_category_gallery_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
    ]
