# Generated by Django 5.2.6 on 2025-09-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_remove_gallery_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
