# Generated by Django 5.2.6 on 2025-09-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
