# Generated by Django 5.2.6 on 2025-09-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_category_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Site.category'),
            preserve_default=False,
        ),
    ]
