# Generated by Django 5.2.6 on 2025-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_gallery_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='english_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='category',
            name='chinese_description',
            field=models.TextField(default='NAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='chinese_name',
            field=models.CharField(default='NAN', max_length=200),
            preserve_default=False,
        ),
    ]
