# Generated by Django 5.2.6 on 2025-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_rename_description_category_english_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
